# **FRUIT HARVEST MANAGEMENT WITH SOIL NUTRIENTS DATA**

**Description:**

The soil nutrient database provides standardized information about the crop nutrient values in India.

The "Fruit Recommender Dataset with Soil Nutrients" Dataset trying to improve crop yield by recommending the right crop to grow.

 **Synopsis:**

 Introduction

 Data Preprocessing

 Normalized data

 Exploratory Data Analysis

 Result

**Problem Statement:** To predict the type of fruit variety based on the soil nutrients

**Dataset source**:https://www.kaggle.com/datasets/manikantasanjayv/crop-recommender-dataset-with-soil-nutrients

**Team Name:**  Clueless Coders


**Team Members:**

Aysha.M

EsakkiAnu.R

Harini.A

**Program:**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns


**Data Collection:**

In [ ]:
dt=pd.read_csv('/content/archive (2).zip')

**Data Preprocessing:**

In [ ]:
dt.drop_duplicates(inplace=True)

In [ ]:
dt.head()

,N,P,K,ph,EC,S,Cu,Fe,Mn,Zn,B,label
0,143,69,217,5.9,0.58,0.23,10.20,116.35,59.96,54.85,21.29,pomegranate
1,170,36,216,5.9,0.15,0.28,15.69,114.20,56.87,31.28,28.62,pomegranate
2,158,66,219,6.8,0.34,0.20,15.29,65.87,51.81,57.12,27.59,pomegranate
3,133,45,207,6.4,0.94,0.21,8.48,103.10,43.81,68.50,47.29,pomegranate
4,132,48,218,6.7,0.54,0.19,5.59,63.40,56.40,46.71,31.04,pomegranate

In [ ]:
dt.label

0      pomegranate
1      pomegranate
2      pomegranate
3      pomegranate
4      pomegranate
          ...
615         potato
616         potato
617         potato
618         potato
619         potato
Name: label, Length: 620, dtype: object

**Label Encoding:**

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
dt.label=le.fit_transform(dt.label)

In [ ]:
dt.head()

     N   P    K   ph    EC     S     Cu      Fe     Mn     Zn      B  label
0  143  69  217  5.9  0.58  0.23  10.20  116.35  59.96  54.85  21.29      3
1  170  36  216  5.9  0.15  0.28  15.69  114.20  56.87  31.28  28.62      3
2  158  66  219  6.8  0.34  0.20  15.29   65.87  51.81  57.12  27.59      3
3  133  45  207  6.4  0.94  0.21   8.48  103.10  43.81  68.50  47.29      3
4  132  48  218  6.7  0.54  0.19   5.59   63.40  56.40  46.71  31.04      3

**X,Y Splitup**

In [ ]:
x=dt.drop(columns=['N','P','ph' , 'S','Cu','Fe','Mn','label'])

In [ ]:
y=dt.label

**Train,Test,Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtr, xte, ytr, yte = train_test_split(x,y,test_size=0.15)

**Algorithm Decision**- Logistic Regression


When independent linear clusters are found

In [ ]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr=lr.fit(xtr,ytr)
ypred=lr.predict(xte)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

**Evaluation matrix**

In [ ]:
from sklearn.metrics import accuracy_score,roc_auc_score, confusion_matrix

In [ ]:
accuracy_score(yte,ypred)

0.9032258064516129

In [ ]:
a=confusion_matrix(yte,ypred)
a

array([[16,  0,  0,  0,  0,  0],
       [ 2, 16,  0,  0,  0,  0],
       [ 3,  0,  9,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  1],
       [ 0,  0,  0,  1, 14,  0],
       [ 0,  0,  0,  2,  0, 18]])

**KNN**- When a group of clusters are separated by a good distance

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k=KNeighborsClassifier(n_neighbors=5)

In [ ]:
k.fit(xtr,ytr)
ypred=k.predict(xte)
print(accuracy_score(yte,ypred))
print(confusion_matrix(yte,ypred))

0.9139784946236559
[[16  0  0  0  0  0]
 [ 1 16  1  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0 11  1  0]
 [ 0  0  1  2 12  0]
 [ 0  0  0  2  0 18]]

**Dumping the logic**

In [ ]:
import pickle as pkl

In [ ]:
pkl.dump(lr,open('label(2).pkl','wb'))